# Generated by Django 3.2.6 on 2021-11-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_product_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content_url',
        ),
    ]
