# Generated by Django 3.2.9 on 2021-11-13 00:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211112_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='users/user_default_bg.png', upload_to=accounts.models.user_directory_path_profile),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='card',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='csv_filename',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='czip',
            field=models.IntegerField(),
        ),
    ]
