# Generated by Django 3.2.6 on 2021-11-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='czip',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='street',
        ),
    ]
