# Generated by Django 3.2.6 on 2021-11-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211122_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='expired',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='dateAA',
            field=models.CharField(choices=[('2021', '2221'), ('2222', '2222'), ('2223', '2223'), ('2224', '2224'), ('2225', '2225'), ('2226', '2226'), ('2227', '2227'), ('2228', '2228')], default='2021', max_length=4),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='dateMM',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=2),
        ),
    ]
